fix(ci-benchmarks): Benchmarks job failing due to duplicate godot class files after moving them to addon

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -93,8 +93,17 @@ jobs:
                   # https://github.com/godotengine/godot/issues/111645
                   # Workaround: Import twice to workaround first editor crash.
                   godot --headless --path godot --import --quit || true
+                  
                   echo "First import expected to crash due to bug. Importing again to workaround crash."
-                  godot --headless --path godot --import --quit
+                  godot --headless --path godot --import --quit | tee godot-import-stdout.txt
+                  
+                  # Check for errors in import output
+                  if awk '/ERROR/ {exit 1}' godot-import-stdout.txt; then
+                    echo "✅ Project import successful"
+                  else
+                    echo "❌ Project import failed - errors detected"
+                    exit 1
+                  fi
 
             - name: Run benchmarks and extract JSON
               working-directory: itest
